language: rust

rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

script:
  - cd engine/src; cargo build --verbose --all; cd ../..
  - cd engine/src; cargo test --verbose --all; cd ../..
