[package]
name = "renderer"
version = "0.1.0"
authors = ["Benjamin Lefaudeux <benjamin.lefaudeux@gmail.com>"]

[dependencies]
rayon = "*"
tobj = "0.1.11"
gdk = "0.11.0"
gdk-pixbuf = "0.7.0"
gtk = "0.7.0"
log = "*"
gio = "0.7.0"