[package]
name = "renderer"
version = "0.1.0"
authors = ["Benjamin Lefaudeux <benjamin.lefaudeux@gmail.com>"]

[dependencies]
rayon = "*"
tobj = "0.1.11"
gdk-pixbuf = "0.7.0"
gtk = "0.7.0"
relm = "0.18.0"
relm-derive = "0.18.0"
